name: build and publish
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/Dave-Swagten/medal.tv-bulk-downloader:latest
          platforms: linux/amd64,linux/arm64
  # TODO:
  # python:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'  # Specify the Python version

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Build package
  #       run: |
  #         python setup.py sdist bdist_wheel

  #     - name: Publish package to PyPI
  #       uses: pypa/gh-action-pypi-publish@v1.5.1
  #       with:
  #         user: ${{ secrets.PYPI_USERNAME }}
  #         password: ${{ secrets.PYPI_PASSWORD }}
